lib: lmb: conditionally include EFI loader notification
Compiling with CONFIG_CC_OPTIMIZE_FOR_DEBUG=y
without CONFIG_EFI_LOADER enabled will result in an
undefined reference to 'efi_add_memory_map_pg'.

The make command is as follows:
    export CROSS_COMPILE=arm-none-eabi- ARCH=arm
    make stm32h750-art-pi_defconfig
    -> General setup -> Optimization level -> Optimize for debugging
    make -j 12
The error message is as follows:
    arm-none-eabi-ld.bfd: lib/lmb.o: in function `lmb_map_update_notify':
    u-boot/lib/lmb.c:458: undefined reference to `efi_add_memory_map_pg'
    make: *** [Makefile:1824：u-boot] Error 1

Using the CONFIG_CC_OPTIMIZE_FOR_SIZE configuration
will not cause an error.My guess is that the compiler
recognizes that this function will not be executed and optimizes it.

As you can see from the lmb_should_notify function,
EFI_LOADER will exit without calling efi_add_memory_map_pg().
So splitting with the CONFIG_EFI_LOADER macro would be a fix.

    ```c
    static bool lmb_should_notify(u32 flags)
    {
        return !lmb.test && !(flags & LMB_NONOTIFY) &&
            CONFIG_IS_ENABLED(EFI_LOADER);
    }
    static int lmb_map_update_notify()
    {
    #if defined(CONFIG_EFI_LOADER)
        if (!lmb_should_notify(flags))
            return 0;
    #endif
    }
    ```

Series-to: Liya Huang <1425075683@qq.com>